update install server

diff --git a/lib/functions/control/fn_install_config b/lib/functions/control/fn_install_config
--- a/lib/functions/control/fn_install_config
+++ b/lib/functions/control/fn_install_config
@@ -1,33 +1,53 @@
 #!/bin/bash
-# LGSM fn_server function
+# LGSM fn_install_config function
 # Author: Daniel Gibbs
 # Website: http://gameservermanagers.com
-# Version: 220315
+# Version: 010715
+
+fn_arkconfig(){
+echo ""
+}
 
 fn_arma3config(){
-mkdir -pv "${servercfgdir}"
-mv -v lgsm-default.server.cfg "${servercfgfullpath}"
-mv -v lgsm-default.network.cfg "${networkcfgfullpath}"
+echo "creating ${servercfg} config file."
+cp -v "${servercfgdefault}" "${servercfgfullpath}"
+sleep 1
+echo "creating ${networkcfg} config file."
+cp -v "${networkcfgdefault}" "${networkcfgfullpath}"
+sleep 1
+echo ""
+}
+
+fn_dstconfig(){
+echo "creating ${servercfg} config file."
+cp -v "${servercfgdefault}" "${servercfgfullpath}"
 sleep 1
 echo ""
 }
 
 fn_goldsourceconfig(){
-echo "creating ${servicename}.cfg config file."
-cp -v lgsm-default.cfg "${servercfgfullpath}"
+echo "creating ${servercfg} config file."
+cp -v "${servercfgdefault}" "${servercfgfullpath}"
 sleep 1
+
+# server.cfg redirects to ${servercfg} for added security
 echo "creating server.cfg."
 touch "${defaultcfg}"
 sleep 1
 echo "creating redirect."
 echo "server.cfg > ${servercfg}."
 echo "exec ${servercfg}" > "${defaultcfg}"
+sleep 1
+
+# creating other files required
 echo "creating listip.cfg."
 sleep 1
 touch "${systemdir}/listip.cfg"
 echo "creating banned.cfg."
 touch "${systemdir}/banned.cfg"
 sleep 1
+
+# allow user to input server name and password
 if [ -z "${autoinstall}" ]; then
 	echo ""
 	echo "Configuring ${gamename} Server"
@@ -45,22 +65,29 @@ echo ""
 }
 
 fn_jc2config(){
-cd "${filesdir}"
-cp -v default_config.lua config.lua
+echo "creating ${servercfg} config file."
+cp -v "${servercfgdefault}" "${servercfgfullpath}"
 sleep 1
 echo ""
 }
 
 fn_serious3config(){
-cp -v lgsm-default.ini ${servercfg}
+echo "creating ${servercfg} config file."
+cp -v "${servercfgdefault}" "${servercfgfullpath}"
+sleep 1
+echo ""
+echo "To edit ${gamename} server config use SS3 Server GUI 3 tool"
+echo "http://mrag.nl/sgui3/"
 sleep 1
 echo ""
 }
 
 fn_sourceconfig(){
-echo "creating ${servicename}.cfg config file."
-cp -v lgsm-default.cfg "${servercfgfullpath}"
+echo "creating ${servercfg} config file."
+cp -v "${servercfgdefault}" "${servercfgfullpath}"
 sleep 1
+
+# server.cfg redirects to ${servercfg} for added security
 echo "creating server.cfg."
 touch "${defaultcfg}"
 sleep 1
@@ -68,6 +95,8 @@ echo "creating redirect."
 echo "server.cfg > ${servercfg}."
 echo "exec ${servercfg}" > "${defaultcfg}"
 sleep 1
+
+# allow user to input server name and password
 if [ -z "${autoinstall}" ]; then
 	echo ""
 	echo "Configuring ${gamename} Server"
@@ -77,16 +106,26 @@ if [ -z "${autoinstall}" ]; then
 	read -p "Enter rcon password: " rconpass
 else
 	servername="${servername}"
-        rconpass="${rcon}"
+	rconpass="${rcon}"
 fi
 sed -i "s/\"hostname\"/\"${servername}\"/g" "${servercfgfullpath}"
 sed -i "s/\"rconpassword\"/\"${rconpass}\"/g" "${servercfgfullpath}"
 echo ""
 }
 
+fn_ts3config(){
+echo "creating blank ${servercfg} config file."
+sleep 1
+echo  "${servercfg} can remain blank by default."
+sleep 1
+echo  "${servercfg} is located in ${servercfgfullpath}."
+sleep 1
+touch "${servercfgfullpath}"
+}
+
 fn_ut99config(){
 echo "${defaultcfg} > ${servercfgfullpath}"
-tr -d '\r' < "${defaultcfg}" > "${servercfgfullpath}"
+tr -d '\r' < "${servercfgdefault}" > "${servercfgfullpath}"
 sleep 1
 echo ""
 echo "Configuring ${gamename} Server"
@@ -102,13 +141,15 @@ echo ""
 }
 
 fn_unity3dconfig(){
-cp -v serverconfig.xml ${servercfg}
+echo "creating ${servercfg} config file."
+cp -v "${servercfgdefault}" "${servercfgfullpath}"
 sleep 1
 echo ""
 }
 
 fn_unreal2config(){
-cp -v "${defaultcfg}" "${servercfgfullpath}"
+echo "creating ${servercfg} config file."
+cp -v "${servercfgdefault}" "${servercfgfullpath}"
 sleep 1
 echo ""
 echo "Configuring ${gamename} Server"
@@ -133,6 +174,16 @@ echo ""
 echo "Creating Configs"
 echo "================================="
 sleep 1
+if [ ! -d "${servercfgdir}" ]; then
+	echo -e "creating ${servercfgdir} dir...\c"
+	mkdir -pv "${servercfgdir}"
+	if [[ $? == 0 ]]; then
+		echo -e  "OK"
+	else
+		echo -e  "FAIL"
+	fi
+fi
+
 if [ "${gamename}" == "ARMA 3" ]; then
 	cd "${systemdir}"
 else
@@ -141,75 +192,87 @@ fi
 	#statements
 if [ "${gamename}" == "7 Days To Die" ]; then
 	fn_unity3dconfig
+elif [ "${gamename}" == "ARK: Survivial Evolved" ]; then
+	fn_arkconfig
 elif [ "${gamename}" == "ARMA 3" ]; then
 	echo -e "downloading lgsm-default.server.cfg & lgsm-default.network.cfg...\c"
-	wget -N --no-check-certificate /dev/null https://raw.githubusercontent.com/dgibbs64/linuxgsm/master/Arma3/cfg/lgsm-default.server.cfg 2>&1 | grep -F HTTP | cut -c45- | uniq
-	wget -N --no-check-certificate /dev/null https://raw.githubusercontent.com/dgibbs64/linuxgsm/master/Arma3/cfg/lgsm-default.network.cfg 2>&1 | grep -F HTTP | cut -c45- | uniq
+	wget -N /dev/null https://raw.githubusercontent.com/dgibbs64/linuxgsm/master/Arma3/cfg/lgsm-default.server.cfg 2>&1 | grep -F HTTP | cut -c45- | uniq
+	wget -N /dev/null https://raw.githubusercontent.com/dgibbs64/linuxgsm/master/Arma3/cfg/lgsm-default.network.cfg 2>&1 | grep -F HTTP | cut -c45- | uniq
 	sleep 1
 	fn_arma3config
+elif [ "${gamename}" == "Black Mesa: Deathmatch" ]; then
+	echo -e "downloading lgsm-default.cfg...\c"
+	wget -N /dev/null https://raw.githubusercontent.com/dgibbs64/linuxgsm/master/BlackMesa/cfg/lgsm-default.cfg 2>&1 | grep -F HTTP | cut -c45- | uniq
+	sleep 1
+	fn_sourceconfig
 elif [ "${gamename}" == "Blade Symphony" ]; then
 	echo -e "downloading lgsm-default.cfg...\c"
-	wget -N --no-check-certificate /dev/null https://raw.githubusercontent.com/dgibbs64/linuxgsm/master/BladeSymphony/cfg/lgsm-default.cfg 2>&1 | grep -F HTTP | cut -c45- | uniq
+	wget -N /dev/null https://raw.githubusercontent.com/dgibbs64/linuxgsm/master/BladeSymphony/cfg/lgsm-default.cfg 2>&1 | grep -F HTTP | cut -c45- | uniq
 	sleep 1
 	fn_goldsourceconfig
 elif [ "${gamename}" == "Counter Strike 1.6" ]; then
 	echo -e "downloading lgsm-default.cfg...\c"
-	wget -N --no-check-certificate /dev/null https://raw.githubusercontent.com/dgibbs64/linuxgsm/master/CounterStrike/cfg/lgsm-default.cfg 2>&1 | grep -F HTTP | cut -c45- | uniq
+	wget -N /dev/null https://raw.githubusercontent.com/dgibbs64/linuxgsm/master/CounterStrike/cfg/lgsm-default.cfg 2>&1 | grep -F HTTP | cut -c45- | uniq
 	sleep 1
 	fn_goldsourceconfig
 elif [ "${gamename}" == "Counter Strike: Condition Zero" ]; then
 	echo -e "downloading lgsm-default.cfg...\c"
-	wget -N --no-check-certificate /dev/null https://raw.githubusercontent.com/dgibbs64/linuxgsm/master/CounterStrikeConditionZero/cfg/lgsm-default.cfg 2>&1 | grep -F HTTP | cut -c45- | uniq
+	wget -N /dev/null https://raw.githubusercontent.com/dgibbs64/linuxgsm/master/CounterStrikeConditionZero/cfg/lgsm-default.cfg 2>&1 | grep -F HTTP | cut -c45- | uniq
 	sleep 1
 	fn_goldsourceconfig
 elif [ "${gamename}" == "Counter Strike: Global Offensive" ]; then
 	echo -e "downloading lgsm-default.cfg...\c"
-	wget -N --no-check-certificate /dev/null https://raw.githubusercontent.com/dgibbs64/linuxgsm/master/CounterStrikeGlobalOffensive/cfg/lgsm-default.cfg 2>&1 | grep -F HTTP | cut -c45- | uniq
+	wget -N /dev/null https://raw.githubusercontent.com/dgibbs64/linuxgsm/master/CounterStrikeGlobalOffensive/cfg/lgsm-default.cfg 2>&1 | grep -F HTTP | cut -c45- | uniq
 	sleep 1
 	fn_sourceconfig
 elif [ "${gamename}" == "Counter Strike: Source" ]; then
 	echo -e "downloading lgsm-default.cfg...\c"
-	wget -N --no-check-certificate /dev/null https://raw.githubusercontent.com/dgibbs64/linuxgsm/master/CounterStrikeSource/cfg/lgsm-default.cfg 2>&1 | grep -F HTTP | cut -c45- | uniq
+	wget -N /dev/null https://raw.githubusercontent.com/dgibbs64/linuxgsm/master/CounterStrikeSource/cfg/lgsm-default.cfg 2>&1 | grep -F HTTP | cut -c45- | uniq
 	sleep 1
 	fn_sourceconfig
 elif [ "${gamename}" == "Day of Defeat" ]; then
 	echo -e "downloading lgsm-default.cfg...\c"
-	wget -N --no-check-certificate /dev/null https://raw.githubusercontent.com/dgibbs64/linuxgsm/master/DayOfDefeat/cfg/lgsm-default.cfg 2>&1 | grep -F HTTP | cut -c45- | uniq
+	wget -N /dev/null https://raw.githubusercontent.com/dgibbs64/linuxgsm/master/DayOfDefeat/cfg/lgsm-default.cfg 2>&1 | grep -F HTTP | cut -c45- | uniq
 	sleep 1
 	fn_goldsourceconfig
 elif [ "${gamename}" == "Day of Defeat: Source" ]; then
 	echo -e "downloading lgsm-default.cfg...\c"
-	wget -N --no-check-certificate /dev/null https://raw.githubusercontent.com/dgibbs64/linuxgsm/master/DayOfDefeatSource/cfg/lgsm-default.cfg 2>&1 | grep -F HTTP | cut -c45- | uniq
+	wget -N /dev/null https://raw.githubusercontent.com/dgibbs64/linuxgsm/master/DayOfDefeatSource/cfg/lgsm-default.cfg 2>&1 | grep -F HTTP | cut -c45- | uniq
 	sleep 1
 	fn_sourceconfig
-elif [ "${gamename}" == "Double Action: Boogaloo" ]; then
-	echo -e "downloading lgsm-default.cfg...\c"
-	wget -N --no-check-certificate /dev/null https://raw.githubusercontent.com/dgibbs64/linuxgsm/master/DoubleActionBoogaloo/cfg/lgsm-default.cfg 2>&1 | grep -F HTTP | cut -c45- | uniq
+elif [ "${gamename}" == "Dont Starve Together" ]; then
+	echo -e "downloading lgsm-default.ini...\c"
+	wget -N /dev/null https://raw.githubusercontent.com/dgibbs64/linuxgsm/master/DontStarveTogether/lgsm-default.ini 2>&1 | grep -F HTTP | cut -c45- | uniq
 	sleep 1
-	fn_sourceconfig
+	fn_dstconfig
+	elif [ "${gamename}" == "Double Action: Boogaloo" ]; then
+		echo -e "downloading lgsm-default.cfg...\c"
+		wget -N /dev/null https://raw.githubusercontent.com/dgibbs64/linuxgsm/master/DoubleActionBoogaloo/cfg/lgsm-default.cfg 2>&1 | grep -F HTTP | cut -c45- | uniq
+		sleep 1
+		fn_sourceconfig
 elif [ "${gamename}" == "Fistful of Frags" ]; then
 	echo -e "downloading lgsm-default.cfg...\c"
-	wget -N --no-check-certificate /dev/null https://raw.githubusercontent.com/dgibbs64/linuxgsm/master/FistfulOfFrags/cfg/lgsm-default.cfg 2>&1 | grep -F HTTP | cut -c45- | uniq
+	wget -N /dev/null https://raw.githubusercontent.com/dgibbs64/linuxgsm/master/FistfulOfFrags/cfg/lgsm-default.cfg 2>&1 | grep -F HTTP | cut -c45- | uniq
 	sleep 1
 	fn_sourceconfig
 elif [ "${gamename}" == "Garry's Mod" ]; then
 	echo -e "downloading lgsm-default.cfg...\c"
-	wget -N --no-check-certificate /dev/null https://raw.githubusercontent.com/dgibbs64/linuxgsm/master/GarrysMod/cfg/lgsm-default.cfg 2>&1 | grep -F HTTP | cut -c45- | uniq
+	wget -N /dev/null https://raw.githubusercontent.com/dgibbs64/linuxgsm/master/GarrysMod/cfg/lgsm-default.cfg 2>&1 | grep -F HTTP | cut -c45- | uniq
 	sleep 1
 	fn_sourceconfig
 elif [ "${gamename}" == "Half Life 2: Deathmatch" ]; then
 	echo -e "downloading lgsm-default.cfg...\c"
-	wget -N --no-check-certificate /dev/null https://raw.githubusercontent.com/dgibbs64/linuxgsm/master/HalfLife2Deathmatch/cfg/lgsm-default.cfg 2>&1 | grep -F HTTP | cut -c45- | uniq
+	wget -N /dev/null https://raw.githubusercontent.com/dgibbs64/linuxgsm/master/HalfLife2Deathmatch/cfg/lgsm-default.cfg 2>&1 | grep -F HTTP | cut -c45- | uniq
 	sleep 1
 	fn_sourceconfig
 elif [ "${gamename}" == "Half Life: Deathmatch Classic" ]; then
 	echo -e "downloading lgsm-default.cfg...\c"
-	wget -N --no-check-certificate /dev/null https://raw.githubusercontent.com/dgibbs64/linuxgsm/master/HalfLifeDeathmatchClassic/cfg/lgsm-default.cfg 2>&1 | grep -F HTTP | cut -c45- | uniq
+	wget -N /dev/null https://raw.githubusercontent.com/dgibbs64/linuxgsm/master/HalfLifeDeathmatchClassic/cfg/lgsm-default.cfg 2>&1 | grep -F HTTP | cut -c45- | uniq
 	sleep 1
 	fn_goldsourceconfig
 elif [ "${gamename}" == "Insurgency" ]; then
 	echo -e "downloading lgsm-default.cfg...\c"
-	wget -N --no-check-certificate /dev/null https://raw.githubusercontent.com/dgibbs64/linuxgsm/master/Insurgency/cfg/lgsm-default.cfg 2>&1 | grep -F HTTP | cut -c45- | uniq
+	wget -N /dev/null https://raw.githubusercontent.com/dgibbs64/linuxgsm/master/Insurgency/cfg/lgsm-default.cfg 2>&1 | grep -F HTTP | cut -c45- | uniq
 	sleep 1
 	fn_sourceconfig
 elif [ "${gamename}" == "Just Cause 2" ]; then
@@ -218,17 +281,17 @@ elif [ "${gamename}" == "Killing Floor" ]; then
 	fn_unreal2config
 elif [ "${gamename}" == "Left 4 Dead" ]; then
 	echo -e "downloading lgsm-default.cfg...\c"
-	wget -N --no-check-certificate /dev/null https://raw.githubusercontent.com/dgibbs64/linuxgsm/master/Left4Dead/cfg/lgsm-default.cfg 2>&1 | grep -F HTTP | cut -c45- | uniq
+	wget -N /dev/null https://raw.githubusercontent.com/dgibbs64/linuxgsm/master/Left4Dead/cfg/lgsm-default.cfg 2>&1 | grep -F HTTP | cut -c45- | uniq
 	sleep 1
 	fn_sourceconfig
 elif [ "${gamename}" == "Left 4 Dead 2" ]; then
 	echo -e "downloading lgsm-default.cfg...\c"
-	wget -N --no-check-certificate /dev/null https://raw.githubusercontent.com/dgibbs64/linuxgsm/master/Left4Dead2/cfg/lgsm-default.cfg 2>&1 | grep -F HTTP | cut -c45- | uniq
+	wget -N /dev/null https://raw.githubusercontent.com/dgibbs64/linuxgsm/master/Left4Dead2/cfg/lgsm-default.cfg 2>&1 | grep -F HTTP | cut -c45- | uniq
 	sleep 1
 	fn_sourceconfig
 elif [ "${gamename}" == "No More Room in Hell" ]; then
 	echo -e "downloading lgsm-default.cfg...\c"
-	wget -N --no-check-certificate /dev/null https://raw.githubusercontent.com/dgibbs64/linuxgsm/master/NoMoreRoomInHell/cfg/lgsm-default.cfg 2>&1 | grep -F HTTP | cut -c45- | uniq
+	wget -N /dev/null https://raw.githubusercontent.com/dgibbs64/linuxgsm/master/NoMoreRoomInHell/cfg/lgsm-default.cfg 2>&1 | grep -F HTTP | cut -c45- | uniq
 	sleep 1
 	fn_sourceconfig
 elif [ "${gamename}" == "Natural Selection 2" ]; then
@@ -239,17 +302,19 @@ elif [ "${gamename}" == "Red Orchestra: Ostfront 41-45" ]; then
 	fn_unreal2config
 elif [ "${gamename}" == "Serious Sam 3: BFE" ]; then
 	echo -e "downloading lgsm-default.ini...\c"
-	wget -N --no-check-certificate /dev/null https://raw.githubusercontent.com/dgibbs64/linuxgsm/master/SeriousSam3BFE/cfg/lgsm-default.ini 2>&1 | grep -F HTTP | cut -c45- | uniq
+	wget -N /dev/null https://raw.githubusercontent.com/dgibbs64/linuxgsm/master/SeriousSam3BFE/cfg/lgsm-default.ini 2>&1 | grep -F HTTP | cut -c45- | uniq
 	sleep 1
 	fn_serious3config
+elif [ "${gamename}" == "Teamspeak 3" ]; then
+	fn_ts3config
 elif [ "${gamename}" == "Team Fortress 2" ]; then
 	echo -e "downloading lgsm-default.cfg...\c"
-	wget -N --no-check-certificate /dev/null https://raw.githubusercontent.com/dgibbs64/linuxgsm/master/TeamFortress2/cfg/lgsm-default.cfg 2>&1 | grep -F HTTP | cut -c45- | uniq
+	wget -N /dev/null https://raw.githubusercontent.com/dgibbs64/linuxgsm/master/TeamFortress2/cfg/lgsm-default.cfg 2>&1 | grep -F HTTP | cut -c45- | uniq
 	sleep 1
 	fn_sourceconfig
 elif [ "${gamename}" == "Team Fortress Classic" ]; then
 	echo -e "downloading lgsm-default.cfg...\c"
-	wget -N --no-check-certificate /dev/null https://raw.githubusercontent.com/dgibbs64/linuxgsm/master/TeamFortressClassic/cfg/lgsm-default.cfg 2>&1 | grep -F HTTP | cut -c45- | uniq
+	wget -N /dev/null https://raw.githubusercontent.com/dgibbs64/linuxgsm/master/TeamFortressClassic/cfg/lgsm-default.cfg 2>&1 | grep -F HTTP | cut -c45- | uniq
 	sleep 1
 	fn_goldsourceconfig
 elif [ "${gamename}" == "Unreal Tournament 2004" ]; then
